repos:
  - repo: local
    hooks:
      - id: check-docs
        name: Check Command Documentation
        description: Ensures that all of the commands in the terminal are included in Hugo.
        language: python
        pass_filenames: false
        args:
          [
            "--ignore-files=settings_controller.py,featflags_controller.py,keys_controller.py,degiro_controller.py,",
            "--ignore-commands=login,al_swe,info_swe,goodness,resources,yf,yolo,from,to",
          ]
        entry: python custom_pre_commit/check_doc.py
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [css, markdown, text, svg]
      - id: trailing-whitespace
        exclude_types: [html, markdown, text]
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: flake8 --ignore=E203,W503 --max-line-length=122 --exclude ./build/pyinstaller/*
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        entry: codespell
        args:
          [
            "--ignore-words-list=vie,hel,zlot,ba,buil,coo,ether,hist,hsi,mape,navagation,operatio,pres,ser,yeld,shold,ist,varian,datas,ake,creat",
            "--quiet-level=2",
            "--skip=./tests,.git,*.css,*.csv,*.html,*.ini,*.ipynb,*.js,*.json,*.lock,*.scss,*.txt,*.yaml,build/pyinstaller/*",
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.960"
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", '--exclude=/setup\.py$']
        additional_dependencies: [types-all]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        name: Strip notebooks output
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint openbb_terminal terminal.py tests
        language: system
        types: [python]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        args:
          ["--baseline", ".secrets.baseline", "--exclude-files", "cassettes/*"]
        exclude: package.lock.json
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
