name: Intel MacOS
env:
  OPENBB_ENABLE_QUICK_EXIT: true
  OPENBB_LOG_COLLECTION: false
  OPENBB_USE_ION: false
  OPENBB_USE_PROMPT_TOOLKIT: false
  PIP_DEFAULT_TIMEOUT: 100
  PYTHONNOUSERSITE: 1
on: workflow_dispatch
jobs:
  Build:
    name: Intel MacOS Build
    runs-on: macos-latest
    steps:
      # Check out repository
      - name: Checkout
        uses: actions/checkout@v2.4.2
      # Set up caching for conda env so that the workflow runs quickly after the first time
      - name: Setup caching for conda packages
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-macos-3-9-${{ hashFiles('build/conda/conda-3-9-env.yaml') }}
      # Set up miniconda using the environment yaml file within the repo
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          channels: conda-forge,defaults
          show-channel-urls: true
          channel-priority: flexible
          environment-file: build/conda/conda-3-9-env.yaml
          activate-environment: build_env
          use-only-tar-bz2: true # Needed for caching some reason
      - name: Run Poetry
        shell: bash -l {0}
        run: poetry install
      - name: Install Pyinstaller
        shell: bash -l {0}
        run: poetry install -E installer
      - name: Install Prediction Modules
        shell: bash -l {0}
        run: poetry install -E prediction
      - name: Run Build Shell Script
        shell: bash -l {0}
        continue-on-error: true # this is here because there is a known error in create-dmg that cannot unmount disks if they are too large
        run: build/pyinstaller/build4mac.sh
        # Saves created artifacts except the icon artifact
      - name: Save Build Artifact Folder
        uses: actions/upload-artifact@v3
        with:
          name: OpenBB Artifact
          path: |
                DMG/OpenBB\ Terminal/.openbb
                DMG/OpenBB\ Terminal/OpenBB\ Terminal
      - name: Run Integration Tests
        shell: bash -l {0}
        run: DMG/OpenBB\ Terminal/.OpenBB/OpenBBTerminal ~/work/OpenBBTerminal/OpenBBTerminal/scripts/*.openbb -t
